---
kind: pipeline
type: docker
name: default

environment:
  SCCACHE_BUCKET: sccache

steps:
  - name: yml_lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: cargo_clippy
    image: hsmtkk/rust-sccache:1.54.1
    commands:
      - cargo clippy
  - name: cargo_test
    image: hsmtkk/rust-sccache:1.54.1
    commands:
      - cargo test
