---
kind: pipeline
type: docker
name: default

environment:
  SCCACHE_ENDPOINT: "gateway.ap1.storjshare.io:443"
  SCCACHE_S3_USE_SSL: "true"
  SCCACHE_BUCKET: sccache

steps:
  - name: yml_lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: cargo_clippy
    image: hsmtkk/rust-sccache:1.54.1
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: storaj_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: storaj_secret_key
    commands:
      - rustup component add clippy
      - cargo clippy
  - name: cargo_test
    image: hsmtkk/rust-sccache:1.54.1
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: storaj_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: storaj_secret_key
    commands:
      - cargo test
